root: true
extends:
  - eslint-config-dmitmel/presets/node
env:
  browser: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  func-names: off
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
        - dynamicImport
  node/no-unsupported-features/es-builtins:
    - error
    - ignores:
        - globalThis
  node/no-unsupported-features/node-builtins:
    - error
    - ignores:
        - fs.promises

  node/no-missing-require: off
  node/no-missing-import: off
  node/no-unpublished-import: off
  node/no-unpublished-require: off
  node/shebang: off
  no-process-exit: off
  no-undef: off
  no-undefined: off
  no-unused-vars: off
  new-cap: off
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"

overrides:
  - files: "**/*.{ts,tsx,mts,cts}"
    extends: eslint-config-dmitmel/presets/typescript-addon
    rules:
      node/no-missing-import: off
      eqeqeq:
        - error
        - always
        - "null": "ignore"
      \@typescript-eslint/no-dynamic-delete: off
      no-return-assign: off
      no-void: off
      consistent-return: off
  - files: "bin/**.{js,mjs,cjs}"
    extends: eslint-config-dmitmel/presets/node
    rules:
      "@typescript-eslint/no-unused-vars": off
      no-undefined: off

  - files: "bin/**.mjs"
    rules:
      node/no-unsupported-features/es-syntax: off

  - files: "**/src/**/*.{ts,tsx,mts,cts}"
    extends: eslint-config-dmitmel/rules/typescript/with-type-checking

  - files: "**/*.d.ts"
    rules:
      no-var: off

  - files: "src/**/*.{ts,tsx,mts,cts}"
    parserOptions:
      project: tsconfig.json

  - files: "src/renderer/**/*.{ts,tsx,mts,cts}"
    rules:
      no-console: error
  - files: "src/renderer/modules/{common,components}/*.{ts,tsx,mts,cts}"
    rules:
      # These files sometimes have checks that are technically unnecessary according to the typedefs,
      # but should help prevent a crash in the case of an unexpected Discord change
      # So we will allow them
      "@typescript-eslint/no-unnecessary-condition": off
