module.exports = Object.freeze({
  SET_SETTING: 'POWERCORD_SETTING_SET',
  DELETE_SETTING: 'POWERCORD_SETTING_DELETE',
  UPDATE_SETTING: 'POWERCORD_SETTING_UPDATE',
  TOGGLE_SETTING: 'POWERCORD_SETTING_TOGGLE',
  UPDATE_SETTINGS: 'POWERCORD_SETTINGS_UPDATE'
});
