/* THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY. */
/* eslint-disable */
/* prettier-ignore */

import {MessageLoader, TypedIntlMessageGetter, HandlerFunction, HookFunction, LinkFunction} from '@discord/intl';

export declare const messagesLoader: MessageLoader;

export declare const messages: {
  /**
   * Key: `Xyo9Z+`
   * 
   * ### Definition
   * ```text
   * Replugged Account
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `es-419`, `th`
   */
  'REPLUGGED_ACCOUNT': TypedIntlMessageGetter<{}>,
  /**
   * Key: `oDaOkA`
   * 
   * ### Definition
   * ```text
   * Open {type} Folder
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_ADDONS_FOLDER_OPEN': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `bQBP1m`
   * 
   * ### Definition
   * ```text
   * Load Missing {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_ADDONS_LOAD_MISSING': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `vX/Z3K`
   * 
   * ### Definition
   * ```text
   * {type} ({count, number})
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_ADDONS_TITLE_COUNT': TypedIntlMessageGetter<{count: number | string, type: any}>,
  /**
   * Key: `ov+bm9`
   * 
   * ### Definition
   * ```text
   * {count, plural, =1 {Author: {author1}} =2 {Authors: {author1} and {author2}} =3 {Authors: {author1}, {author2}, and {author3}} other {Authors: {author1}, {author2}, {author3}, and {others, plural, =1 {# other} other {# others}}}}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_ADDON_AUTHORS': TypedIntlMessageGetter<{author1: any, author2: any, author3: any, count: number, others: number | string}>,
  /**
   * Key: `XuYvz8`
   * 
   * ### Definition
   * ```text
   * by {author1}, {author2}, {author3}, and {count, plural, =1 {# other} other {# others}}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_ADDON_AUTHORS_MANY': TypedIntlMessageGetter<{author1: any, author2: any, author3: any, count: number | string}>,
  /**
   * Key: `H/KS92`
   * 
   * ### Definition
   * ```text
   * by {author1}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_ADDON_AUTHORS_ONE': TypedIntlMessageGetter<{author1: any}>,
  /**
   * Key: `2rQVGW`
   * 
   * ### Definition
   * ```text
   * by {author1}, {author2}, and {author3}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_ADDON_AUTHORS_THREE': TypedIntlMessageGetter<{author1: any, author2: any, author3: any}>,
  /**
   * Key: `t0iUje`
   * 
   * ### Definition
   * ```text
   * by {author1} and {author2}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_ADDON_AUTHORS_TWO': TypedIntlMessageGetter<{author1: any, author2: any}>,
  /**
   * Key: `r7ScHI`
   * 
   * ### Definition
   * ```text
   * Browse {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`
   */
  'REPLUGGED_ADDON_BROWSE': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `oYIqAf`
   * 
   * ### Definition
   * ```text
   * Delete {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_ADDON_DELETE': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `Vu4iKE`
   * 
   * ### Definition
   * ```text
   * Unreviewed {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`
   */
  'REPLUGGED_ADDON_NOT_REVIEWED': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `QkGpp9`
   * 
   * ### Definition
   * ```text
   * This {type} has not been reviewed by the Replugged team and could harm your computer. Use at your own risk.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`
   */
  'REPLUGGED_ADDON_NOT_REVIEWED_DESC': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `SxMPWy`
   * 
   * ### Definition
   * ```text
   * Open {type} Page
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_ADDON_PAGE_OPEN': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `kxDIJw`
   * 
   * ### Definition
   * ```text
   * Open {type} Profile
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_ADDON_PROFILE_OPEN': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `BfSK7f`
   * 
   * ### Definition
   * ```text
   * Reload {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_ADDON_RELOAD': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `rDXyPc`
   * 
   * ### Definition
   * ```text
   * Open {type} Settings
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_ADDON_SETTINGS': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `Re3C6u`
   * 
   * ### Definition
   * ```text
   * Choose Theme Preset
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `it`, `ja`, `ko`, `lt`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_ADDON_SETTINGS_THEME_PRESET': TypedIntlMessageGetter<{}>,
  /**
   * Key: `WqqBfE`
   * 
   * ### Definition
   * ```text
   * Uninstall {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_ADDON_UNINSTALL': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `n8oLCZ`
   * 
   * ### Definition
   * ```text
   * Are you sure you want to uninstall this {type}? This cannot be undone.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_ADDON_UNINSTALL_PROMPT_BODY': TypedIntlMessageGetter<{type: 'plugin' | any | string}>,
  /**
   * Key: `x8YaWh`
   * 
   * ### Definition
   * ```text
   * Replugged Server Booster
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `th`
   */
  'REPLUGGED_BADGES_BOOSTER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `vtpx0h`
   * 
   * ### Definition
   * ```text
   * Replugged Contributor
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `es-419`, `th`
   */
  'REPLUGGED_BADGES_CONTRIBUTOR': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ueaJhp`
   * 
   * ### Definition
   * ```text
   * Replugged Developer
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `es-419`, `th`
   */
  'REPLUGGED_BADGES_DEVELOPER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `GeyL71`
   * 
   * ### Definition
   * ```text
   * Replugged Early User
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `es-419`, `th`
   */
  'REPLUGGED_BADGES_EARLY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `gQ9ld8`
   * 
   * ### Definition
   * ```text
   * Replugged Bug Hunter
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `es-419`, `th`
   */
  'REPLUGGED_BADGES_HUNTER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `K87yaR`
   * 
   * ### Definition
   * ```text
   * Replugged Staff
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `es-419`, `th`
   */
  'REPLUGGED_BADGES_STAFF': TypedIntlMessageGetter<{}>,
  /**
   * Key: `XSdK+b`
   * 
   * ### Definition
   * ```text
   * Replugged Support
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `es-419`, `th`
   */
  'REPLUGGED_BADGES_SUPPORT': TypedIntlMessageGetter<{}>,
  /**
   * Key: `AMqRmC`
   * 
   * ### Definition
   * ```text
   * Replugged Translator
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `es-419`, `th`
   */
  'REPLUGGED_BADGES_TRANSLATOR': TypedIntlMessageGetter<{}>,
  /**
   * Key: `nnLVsY`
   * 
   * ### Definition
   * ```text
   * Download {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hr`, `th`
   */
  'REPLUGGED_BUTTON_INSTALLER_DOWNLOAD': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `E6bNoI`
   * 
   * ### Definition
   * ```text
   * {type} Installed
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hr`, `th`
   */
  'REPLUGGED_BUTTON_INSTALLER_INSTALLED': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `j9kNoh`
   * 
   * ### Definition
   * ```text
   * Choose which addon to enable
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_ADDONS_OPTION_ADDON_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `AYihyw`
   * 
   * ### Definition
   * ```text
   * Disable a plugin or theme
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hr`, `th`
   */
  'REPLUGGED_COMMAND_DISABLE_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `kxd08G`
   * 
   * ### Definition
   * ```text
   * {type} {name} has been disabled!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_DISABLE_MESSAGE_ENABLED': TypedIntlMessageGetter<{name: any, type: any}>,
  /**
   * Key: `2VoRpS`
   * 
   * ### Definition
   * ```text
   * disable
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_DISABLE_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `8yBta2`
   * 
   * ### Definition
   * ```text
   * Choose which addon to disable
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_DISABLE_OPTION_ADDON_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `14Ixln`
   * 
   * ### Definition
   * ```text
   * addon
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_DISABLE_OPTION_ADDON_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `OcnVfy`
   * 
   * ### Definition
   * ```text
   * Enable a plugin or theme
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `th`
   */
  'REPLUGGED_COMMAND_ENABLE_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `SB+cDY`
   * 
   * ### Definition
   * ```text
   * {type} {name} has been enabled!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_ENABLE_MESSAGE_ENABLED': TypedIntlMessageGetter<{name: any, type: any}>,
  /**
   * Key: `I46ICz`
   * 
   * ### Definition
   * ```text
   * enable
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_ENABLE_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `mgPYDe`
   * 
   * ### Definition
   * ```text
   * addon
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_ENABLE_OPTION_ADDON_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `0su4/g`
   * 
   * ### Definition
   * ```text
   * Something went wrong, please try again later. If this issue persists, please contact the Replugged team.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_ERROR_GENERIC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `uEKO6N`
   * 
   * ### Definition
   * ```text
   * Install a plugin or theme
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `ru`, `sv-SE`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_INSTALL_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ccp7Mi`
   * 
   * ### Definition
   * ```text
   * install
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `ru`, `sv-SE`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_INSTALL_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `fw8KhN`
   * 
   * ### Definition
   * ```text
   * Identifier of the addon to install from the source
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_INSTALL_OPTION_ADDON_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `qrawCd`
   * 
   * ### Definition
   * ```text
   * addon
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_INSTALL_OPTION_ADDON_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `7eLI9F`
   * 
   * ### Definition
   * ```text
   * If the source has multiple addons, specify which one to install
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_INSTALL_OPTION_ID_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `4LCo9O`
   * 
   * ### Definition
   * ```text
   * id
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `ru`, `sv-SE`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_INSTALL_OPTION_ID_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `cfzF9J`
   * 
   * ### Definition
   * ```text
   * Source to install the addon from
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_INSTALL_OPTION_SOURCE_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `fuLlFq`
   * 
   * ### Definition
   * ```text
   * source
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `ru`, `sv-SE`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_INSTALL_OPTION_SOURCE_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `99AWnt`
   * 
   * ### Definition
   * ```text
   * List all plugins or themes
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `CCQadk`
   * 
   * ### Definition
   * ```text
   * You need to specify whether to send a plugin or theme list
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `es-ES`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_ERROR_SPECIFY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `4U9kk3`
   * 
   * ### Definition
   * ```text
   * Disabled {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_HEADER_DISABLED': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `yPSO4L`
   * 
   * ### Definition
   * ```text
   * Enabled {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_HEADER_ENABLED': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `edMBSD`
   * 
   * ### Definition
   * ```text
   * list
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `0wF2gt`
   * 
   * ### Definition
   * ```text
   * Share the list publicly in chat
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_OPTION_SEND_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `lgmT32`
   * 
   * ### Definition
   * ```text
   * send
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_OPTION_SEND_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `IRl+z1`
   * 
   * ### Definition
   * ```text
   * Both
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_OPTION_STATUS_CHOICE_BOTH': TypedIntlMessageGetter<{}>,
  /**
   * Key: `EZPH09`
   * 
   * ### Definition
   * ```text
   * Disabled
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `es-ES`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_OPTION_STATUS_CHOICE_DISABLED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Vx9HW+`
   * 
   * ### Definition
   * ```text
   * Enabled
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `es-ES`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_OPTION_STATUS_CHOICE_ENABLED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `asrAw7`
   * 
   * ### Definition
   * ```text
   * Whether to show addons that are enabled, disabled or both
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_OPTION_STATUS_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `kwqOfG`
   * 
   * ### Definition
   * ```text
   * status
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_OPTION_STATUS_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `+4SVXj`
   * 
   * ### Definition
   * ```text
   * List Plugins
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `sv-SE`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_OPTION_TYPE_CHOICE_PLUGIN': TypedIntlMessageGetter<{}>,
  /**
   * Key: `uZAN3D`
   * 
   * ### Definition
   * ```text
   * List Themes
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `sv-SE`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_OPTION_TYPE_CHOICE_THEME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `JvNekX`
   * 
   * ### Definition
   * ```text
   * What type of addons to show
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_OPTION_TYPE_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `MJhj3Z`
   * 
   * ### Definition
   * ```text
   * type
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_OPTION_TYPE_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `lsDaLy`
   * 
   * ### Definition
   * ```text
   * Include version numbers in the list
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_OPTION_VERSION_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `9k1eE6`
   * 
   * ### Definition
   * ```text
   * version
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `sv-SE`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_LIST_OPTION_VERSION_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ZDurVW`
   * 
   * ### Definition
   * ```text
   * Reload a plugin or theme
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `lt`, `th`
   */
  'REPLUGGED_COMMAND_RELOAD_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `zr04NU`
   * 
   * ### Definition
   * ```text
   * {type} {name} has been reloaded!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_RELOAD_MESSAGE_ENABLED': TypedIntlMessageGetter<{name: any, type: any}>,
  /**
   * Key: `hoytSk`
   * 
   * ### Definition
   * ```text
   * reload
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_RELOAD_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `trfssE`
   * 
   * ### Definition
   * ```text
   * Choose which addon to reload
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_RELOAD_OPTION_ADDON_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `OBctby`
   * 
   * ### Definition
   * ```text
   * addon
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_RELOAD_OPTION_ADDON_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `73G4zP`
   * 
   * ### Definition
   * ```text
   * Success
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_COMMAND_SUCCESS_GENERIC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `zENqYa`
   * 
   * ### Definition
   * ```text
   * Install
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_CONFIRM_INSTALL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `5A4ZGk`
   * 
   * ### Definition
   * ```text
   * You are currently running Replugged in developer mode and Replugged will not be able to update itself. [Switch to production mode]({url}).
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`
   */
  'REPLUGGED_DEVELOPER_MODE_WARNING': TypedIntlMessageGetter<{$link?: LinkFunction, url: any}>,
  /**
   * Key: `noTXKF`
   * 
   * ### Definition
   * ```text
   * {name} is already installed.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `th`
   */
  'REPLUGGED_ERROR_ALREADY_INSTALLED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `0D5GG0`
   * 
   * ### Definition
   * ```text
   * An error occurred while executing the command:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `lt`, `th`
   */
  'REPLUGGED_ERROR_AN_ERROR_OCCURRED_COMMAND': TypedIntlMessageGetter<{}>,
  /**
   * Key: `LacFoP`
   * 
   * ### Definition
   * ```text
   * Check the console for more details.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `lt`, `th`
   */
  'REPLUGGED_ERROR_CHECK_CONSOLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `BS/AJM`
   * 
   * ### Definition
   * ```text
   * Replugged Translations
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `lt`, `no`, `ro`, `sv-SE`, `th`
   */
  'REPLUGGED_I18N': TypedIntlMessageGetter<{}>,
  /**
   * Key: `5wPKhc`
   * 
   * ### Definition
   * ```text
   * Want to help translate Replugged? Go to our [Weblate]({weblateUrl})!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_I18N_CONTRIBUTE': TypedIntlMessageGetter<{$link?: LinkFunction, weblateUrl: any}>,
  /**
   * Key: `hrc762`
   * 
   * ### Definition
   * ```text
   * Replugged: {translated,number}% translated
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_I18N_TRANSLATED_PERCENTAGE': TypedIntlMessageGetter<{translated: number | string}>,
  /**
   * Key: `0impV8`
   * 
   * ### Definition
   * ```text
   * Do you want to install {name} {authors}?
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_INSTALLER_INSTALL_PROMPT_BODY': TypedIntlMessageGetter<{authors: any, name: any}>,
  /**
   * Key: `/omzDw`
   * 
   * ### Definition
   * ```text
   * View in Store
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`, `zh-CN`
   */
  'REPLUGGED_INSTALLER_OPEN_STORE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Cng03W`
   * 
   * ### Definition
   * ```text
   * Install {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `lt`, `th`
   */
  'REPLUGGED_INSTALL_MODAL_HEADER': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `BfrDAx`
   * 
   * ### Definition
   * ```text
   * Link it now
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_LINK_NOW': TypedIntlMessageGetter<{}>,
  /**
   * Key: `wUhy5u`
   * 
   * ### Definition
   * ```text
   * {count, plural, =1 {# match} other {# matches}}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `lt`, `no`, `ro`, `sv-SE`, `th`, `zh-CN`
   */
  'REPLUGGED_LIST_RESULTS': TypedIntlMessageGetter<{count: number | string}>,
  /**
   * Key: `EOJEBw`
   * 
   * ### Definition
   * ```text
   * You are currently on Replugged's Nightly branch. Updates may be unstable. Switch to Stable for a more reliable and officially supported experience.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `en-GB`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `it`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_NIGHTLY_RELEASE_WARNING': TypedIntlMessageGetter<{}>,
  /**
   * Key: `neLAkZ`
   * 
   * ### Definition
   * ```text
   * Join Server
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_NOTICES_JOIN_SERVER_BUTTON': TypedIntlMessageGetter<{}>,
  /**
   * Key: `zKRtMB`
   * 
   * ### Definition
   * ```text
   * Welcome! Replugged has been successfully injected into your Discord client. Feel free to join our Discord server for announcements, support and more!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_NOTICES_WELCOME_NEW_USER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `+cl+rT`
   * 
   * ### Definition
   * ```text
   * No {type} installed.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_NO_ADDONS_INSTALLED': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `nT98BV`
   * 
   * ### Definition
   * ```text
   * No {type} matched your search.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_NO_ADDON_RESULTS': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `nrTCTQ`
   * 
   * ### Definition
   * ```text
   * Plugin
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_PLUGIN': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Jyz+XY`
   * 
   * ### Definition
   * ```text
   * Plugins
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `es-419`, `hi`, `th`
   */
  'REPLUGGED_PLUGINS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `sl1Dvd`
   * 
   * ### Definition
   * ```text
   * View Repo
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `hr`, `no`, `th`
   */
  'REPLUGGED_PLUGIN_EMBED_VIEW_REPO': TypedIntlMessageGetter<{}>,
  /**
   * Key: `OjncuB`
   * 
   * ### Definition
   * ```text
   * {name} requires a reload to work properly. Reload now?
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_PLUGIN_INSTALL_RELOAD_PROMPT_BODY': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `NhWNBd`
   * 
   * ### Definition
   * ```text
   * Quick CSS
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_QUICKCSS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `pUuDNj`
   * 
   * ### Definition
   * ```text
   * Apply Changes
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_QUICKCSS_CHANGES_APPLY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Nk3LNs`
   * 
   * ### Definition
   * ```text
   * Open Quick CSS Folder
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_QUICKCSS_FOLDER_OPEN': TypedIntlMessageGetter<{}>,
  /**
   * Key: `e5G3RN`
   * 
   * ### Definition
   * ```text
   * Search for a {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_SEARCH_FOR_ADDON': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `U0OONn`
   * 
   * ### Definition
   * ```text
   * Replugged Settings
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `en-GB`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `it`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `wxHqIq`
   * 
   * ### Definition
   * ```text
   * Show Addon Embeds
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`, `zh-CN`
   */
  'REPLUGGED_SETTINGS_ADDON_EMBEDS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `T1XII9`
   * 
   * ### Definition
   * ```text
   * Show a card with information on an addon when a store/install link is shared in chat.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`, `zh-CN`
   */
  'REPLUGGED_SETTINGS_ADDON_EMBEDS_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `vdzF9i`
   * 
   * ### Definition
   * ```text
   * Don't touch stuff in here if you don't know what you're doing. Unexpected things can happen to your cat.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_SETTINGS_ADVANCED_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `oiDUN3`
   * 
   * ### Definition
   * ```text
   * Backend URL
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_SETTINGS_BACKEND': TypedIntlMessageGetter<{}>,
  /**
   * Key: `zE/g8l`
   * 
   * ### Definition
   * ```text
   * URL used to fetch some assets and to query Replugged's REST API.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_SETTINGS_BACKEND_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Apex2t`
   * 
   * ### Definition
   * ```text
   * Enable Replugged Badges
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `lt`, `no`, `ro`, `sv-SE`, `th`
   */
  'REPLUGGED_SETTINGS_BADGES': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Vtw/EL`
   * 
   * ### Definition
   * ```text
   * Show custom Replugged badges on user profiles.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `lt`, `no`, `ro`, `sv-SE`, `th`
   */
  'REPLUGGED_SETTINGS_BADGES_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `5D5ltO`
   * 
   * ### Definition
   * ```text
   * Custom Title Bar
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `nl`, `no`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_CUSTOM_TITLE_BAR': TypedIntlMessageGetter<{}>,
  /**
   * Key: `x5PfoO`
   * 
   * ### Definition
   * ```text
   * Use Discord's custom title bar instead of the system title bar. **Requires restart**.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `nl`, `no`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_CUSTOM_TITLE_BAR_DESC': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `6RMznQ`
   * 
   * ### Definition
   * ```text
   * Development Tools
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_DEVELOPMENT_TOOLS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Zy83NY`
   * 
   * ### Definition
   * ```text
   * Disable Minimum Window Size
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_DISABLE_MIN_SIZE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `5yUVWV`
   * 
   * ### Definition
   * ```text
   * Remove Discord's minimum window size restrictions. **Requires restart**.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_DISABLE_MIN_SIZE_DESC': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `ET71DC`
   * 
   * ### Definition
   * ```text
   * Enable Discord Internal DevTools
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_DISCORD_DEVTOOLS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `DMs+IV`
   * 
   * ### Definition
   * ```text
   * Replaces the help button in the title bar with Discord's internal developer tools (different from Chrome DevTools). This setting requires Discord experiments to be enabled first. **Requires restart**.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_DISCORD_DEVTOOLS_DESC': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `ObxHdj`
   * 
   * ### Definition
   * ```text
   * Enable Discord Experiments
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_SETTINGS_DISCORD_EXPERIMENTS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `efBu/G`
   * 
   * ### Definition
   * ```text
   * Unlocks Discord's experiments tab and developer options in settings. **Requires restart**.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_DISCORD_EXPERIMENTS_DESC': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `cmmlCC`
   * 
   * ### Definition
   * ```text
   * Enabling this gives you access to features that can be detected by Discord and may result in an ****account termination****. Replugged is **not responsible** for what you do with this feature. Leave it disabled if you are unsure. The Replugged Team will **not** provide any support regarding any experiment.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_SETTINGS_DISCORD_EXPERIMENTS_WARNING': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `V58dvZ`
   * 
   * ### Definition
   * ```text
   * Component stack:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_SETTINGS_ERROR_COMPONENT_STACK': TypedIntlMessageGetter<{}>,
  /**
   * Key: `qlA8In`
   * 
   * ### Definition
   * ```text
   * Something went wrong rendering this element!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_SETTINGS_ERROR_HEADER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `em6Xqe`
   * 
   * ### Definition
   * ```text
   * Plugin: {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `ru`, `sv-SE`, `th`, `vi`, `zh-CN`
   */
  'REPLUGGED_SETTINGS_ERROR_PLUGIN_NAME': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `sC+4pW`
   * 
   * ### Definition
   * ```text
   * An error occurred while rendering settings panel.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_SETTINGS_ERROR_RENDER_PANEL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `aXsXWx`
   * 
   * ### Definition
   * ```text
   * Check console for details.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_SETTINGS_ERROR_SUB_HEADER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `RbreAP`
   * 
   * ### Definition
   * ```text
   * Keep Token Stored
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_SETTINGS_KEEP_TOKEN': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Z/7+YM`
   * 
   * ### Definition
   * ```text
   * Prevents Discord from removing your token from localStorage, reducing the numbers of unwanted logouts. **Requires restart**.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_SETTINGS_KEEP_TOKEN_DESC': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `eXvP6I`
   * 
   * ### Definition
   * ```text
   * Automatically Apply Quick CSS
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`
   */
  'REPLUGGED_SETTINGS_QUICKCSS_AUTO_APPLY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `YPxTld`
   * 
   * ### Definition
   * ```text
   * Automatically apply changes to Quick CSS as you type.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`
   */
  'REPLUGGED_SETTINGS_QUICKCSS_AUTO_APPLY_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `iAl998`
   * 
   * ### Definition
   * ```text
   * Enable Quick CSS
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_QUICKCSS_ENABLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `pKkVIp`
   * 
   * ### Definition
   * ```text
   * Apply custom styles to Discord instantly. Change colors, layout, and appearance in real time without installing themes.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_QUICKCSS_ENABLE_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ojp799`
   * 
   * ### Definition
   * ```text
   * Enable React DevTools
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`
   */
  'REPLUGGED_SETTINGS_REACT_DEVTOOLS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `CXRYCm`
   * 
   * ### Definition
   * ```text
   * Loads the React DevTools extension, allowing you to inspect the React tree and debug more easily. **Requires restart**.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`
   */
  'REPLUGGED_SETTINGS_REACT_DEVTOOLS_DESC': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `7VpRff`
   * 
   * ### Definition
   * ```text
   * Failed to download React DevTools.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`
   */
  'REPLUGGED_SETTINGS_REACT_DEVTOOLS_FAILED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `8XW5yc`
   * 
   * ### Definition
   * ```text
   * Release Branch
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `en-GB`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `it`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_RELEASE_BRANCH': TypedIntlMessageGetter<{}>,
  /**
   * Key: `mk6xTE`
   * 
   * ### Definition
   * ```text
   * Stable will give you the officially tested and reliable version, while Nightly provides the latest changes and features directly from the github, which may be less stable.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `en-GB`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `it`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_RELEASE_BRANCH_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `qkh2nZ`
   * 
   * ### Definition
   * ```text
   * Nightly
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `en-GB`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `it`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_RELEASE_BRANCH_NIGHTLY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `g9f/7e`
   * 
   * ### Definition
   * ```text
   * Stable
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `en-GB`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `it`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_RELEASE_BRANCH_STABLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `LBwcjQ`
   * 
   * ### Definition
   * ```text
   * This setting requires you to restart Discord to take effect. Do you want to restart Discord now?
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_SETTINGS_RESTART': TypedIntlMessageGetter<{}>,
  /**
   * Key: `l8U+/v`
   * 
   * ### Definition
   * ```text
   * Restart Required
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`, `zh-CN`
   */
  'REPLUGGED_SETTINGS_RESTART_TITLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `e6ACBb`
   * 
   * ### Definition
   * ```text
   * Background Material
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `it`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_TRANSPARENCY_BG_MATERIAL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `sO01jJ`
   * 
   * ### Definition
   * ```text
   * Vibrancy
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `it`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_TRANSPARENCY_VIBRANCY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `F1Fb1H`
   * 
   * ### Definition
   * ```text
   * Transparent Window
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `es-ES`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`, `zh-CN`
   */
  'REPLUGGED_SETTINGS_TRANSPARENT': TypedIntlMessageGetter<{}>,
  /**
   * Key: `N8g5S0`
   * 
   * ### Definition
   * ```text
   * Makes the Discord window transparent, primarily useful for theming. **Requires restart**.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `es-ES`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`, `zh-CN`
   */
  'REPLUGGED_SETTINGS_TRANSPARENT_DESC': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `x4OZi+`
   * 
   * ### Definition
   * ```text
   * **Hardware acceleration** may need to be turned **off**. In some cases, you may experience a black background, such as when the window is cut off at the top or bottom due to the monitor resolution, or when the development tools are open and docked.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `es-ES`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`, `uk`, `vi`, `zh-CN`
   */
  'REPLUGGED_SETTINGS_TRANSPARENT_ISSUES_LINUX': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `KZ4twt`
   * 
   * ### Definition
   * ```text
   * This will break **window snapping**. In some cases, you may experience a black background, such as when the window is cut off at the top or bottom due to the monitor resolution, or when the development tools are open and docked.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `sv-SE`, `th`, `uk`, `vi`, `zh-CN`
   */
  'REPLUGGED_SETTINGS_TRANSPARENT_ISSUES_WINDOWS': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `J3A61V`
   * 
   * ### Definition
   * ```text
   * Window Customization
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_WINDOW': TypedIntlMessageGetter<{}>,
  /**
   * Key: `XuDbXP`
   * 
   * ### Definition
   * ```text
   * Manage the Discord window appearance and behavior.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_WINDOW_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `fXfpW2`
   * 
   * ### Definition
   * ```text
   * Keep Replugged After Updates
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_WIN_UPDATER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `0ljedv`
   * 
   * ### Definition
   * ```text
   * Automatically reapplies Replugged after Discord updates.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_SETTINGS_WIN_UPDATER_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `b2oqX9`
   * 
   * ### Definition
   * ```text
   * Snippet Applied
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_SNIPPET_APPLIED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Fhn1M4`
   * 
   * ### Definition
   * ```text
   * Apply Snippet
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_SNIPPET_APPLY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `TTn6PF`
   * 
   * ### Definition
   * ```text
   * Snippet from #css-snippets applied the {date, date, medium} at {date, time, medium}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `ko`, `th`
   */
  'REPLUGGED_SNIPPET_LINE1': TypedIntlMessageGetter<{date: Date | number}>,
  /**
   * Key: `vL1+gu`
   * 
   * ### Definition
   * ```text
   * Created by {authorTag} ({authorId})
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_SNIPPET_LINE2': TypedIntlMessageGetter<{authorId: any, authorTag: any}>,
  /**
   * Key: `haZx54`
   * 
   * ### Definition
   * ```text
   * Store
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-ES`, `fr`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `ro`, `ru`, `sv-SE`, `vi`, `zh-CN`
   */
  'REPLUGGED_STORE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `kZXj5E`
   * 
   * ### Definition
   * ```text
   * Theme
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_THEME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `nivuVj`
   * 
   * ### Definition
   * ```text
   * Themes
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_THEMES': TypedIntlMessageGetter<{}>,
  /**
   * Key: `wrIbiY`
   * 
   * ### Definition
   * ```text
   * Failed to load missing {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_ADDONS_LOAD_MISSING_FAILED': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `pNMhv1`
   * 
   * ### Definition
   * ```text
   * Loaded missing {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_ADDONS_LOAD_MISSING_SUCCESS': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `LV9nQ6`
   * 
   * ### Definition
   * ```text
   * Failed to disable {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `nl`, `no`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_TOAST_ADDON_DISABLE_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `bikK6v`
   * 
   * ### Definition
   * ```text
   * Disabled {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_ADDON_DISABLE_SUCCESS': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `j+ClUm`
   * 
   * ### Definition
   * ```text
   * Failed to enable {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `ja`, `ko`, `lt`, `nl`, `no`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_TOAST_ADDON_ENABLE_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `k0hIQz`
   * 
   * ### Definition
   * ```text
   * Enabled {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_ADDON_ENABLE_SUCCESS': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `iG2TFU`
   * 
   * ### Definition
   * ```text
   * Failed to reload {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_ADDON_RELOAD_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `3ZmGZI`
   * 
   * ### Definition
   * ```text
   * Reloaded {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_ADDON_RELOAD_SUCCESS': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `3L5Egm`
   * 
   * ### Definition
   * ```text
   * Failed to toggle {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_ADDON_TOGGLE_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `IO1HHr`
   * 
   * ### Definition
   * ```text
   * Failed to uninstall {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_ADDON_UNINSTALL_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `Dthsfl`
   * 
   * ### Definition
   * ```text
   * Uninstalled {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_ADDON_UNINSTALL_SUCCESS': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `CDqdr6`
   * 
   * ### Definition
   * ```text
   * Install canceled
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_INSTALLER_ADDON_CANCELED_INSTALL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `1P0W0i`
   * 
   * ### Definition
   * ```text
   * Failed to get info for addon
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_INSTALLER_ADDON_FETCH_INFO_FAILED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `1RiUEy`
   * 
   * ### Definition
   * ```text
   * Failed to install {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_INSTALLER_ADDON_INSTALL_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `/YMwrn`
   * 
   * ### Definition
   * ```text
   * {name} installed successfully
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_INSTALLER_ADDON_INSTALL_SUCCESS': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `NqlJ3+`
   * 
   * ### Definition
   * ```text
   * {name} was installed but could not be loaded
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_INSTALLER_ADDON_LOAD_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `rLb2kN`
   * 
   * ### Definition
   * ```text
   * Quick CSS reloaded
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_TOAST_QUICKCSS_RELOAD': TypedIntlMessageGetter<{}>,
  /**
   * Key: `TGExol`
   * 
   * ### Definition
   * ```text
   * Switched to preset {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `it`, `ja`, `ko`, `lt`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_TOAST_THEME_PRESET_CHANGED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `oSw5A+`
   * 
   * ### Definition
   * ```text
   * Failed to change preset for {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `cs`, `da`, `de`, `el`, `es-419`, `es-ES`, `fi`, `fr`, `hi`, `hr`, `hu`, `it`, `ja`, `ko`, `lt`, `no`, `pl`, `pt-BR`, `ro`, `ru`, `sv-SE`, `th`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'REPLUGGED_TOAST_THEME_PRESET_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `VowTIp`
   * 
   * ### Definition
   * ```text
   * {count, plural, =1 {# update is} other {# updates are}} available.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `ro`, `th`
   */
  'REPLUGGED_UPDATES_AVAILABLE': TypedIntlMessageGetter<{count: number | string}>,
  /**
   * Key: `+bwUnC`
   * 
   * ### Definition
   * ```text
   * Reload Required
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_AWAITING_RELOAD_TITLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `4PckvA`
   * 
   * ### Definition
   * ```text
   * Check for Updates
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_CHECK': TypedIntlMessageGetter<{}>,
  /**
   * Key: `DCXylt`
   * 
   * ### Definition
   * ```text
   * Enable Updates
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_ENABLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `0WdWvN`
   * 
   * ### Definition
   * ```text
   * Some updates failed!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_FAILED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `JlkmxV`
   * 
   * ### Definition
   * ```text
   * Force Update
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_FORCE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `c2FNB+`
   * 
   * ### Definition
   * ```text
   * Last checked: {date}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_LAST_CHECKED': TypedIntlMessageGetter<{date: any}>,
  /**
   * Key: `27q8zX`
   * 
   * ### Definition
   * ```text
   * Open Updater
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPEN_UPDATER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `X0pjL/`
   * 
   * ### Definition
   * ```text
   * Check for updates automatically
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_AUTO': TypedIntlMessageGetter<{}>,
  /**
   * Key: `8Ko1gH`
   * 
   * ### Definition
   * ```text
   * Replugged will automatically check for updates and show you an alert when one is available. Updates will not be installed until you choose to update it. Only official addons will be checked automatically.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_AUTO_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `aB8UjF`
   * 
   * ### Definition
   * ```text
   * Open Change Log
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_CHANGE_LOGS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `DM7iqt`
   * 
   * ### Definition
   * ```text
   * Missed the change log, or want to see it again?
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_CHANGE_LOGS_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ftHbLm`
   * 
   * ### Definition
   * ```text
   * Update Concurrency Limit
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_CONCURRENCY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `fmENlC`
   * 
   * ### Definition
   * ```text
   * How many concurrent tasks Replugged will run in background to check for updates. Minimum 1. If unsure, leave 2.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_CONCURRENCY_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `D0hYHA`
   * 
   * ### Definition
   * ```text
   * Update Check Interval
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_INTERVAL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `QUYCx3`
   * 
   * ### Definition
   * ```text
   * How frequently Replugged will check for updates. Minimum 10 minutes.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_INTERVAL_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Efudw+`
   * 
   * ### Definition
   * ```text
   * Change Release Channel
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_RELEASE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `MrEYwZ`
   * 
   * ### Definition
   * ```text
   * You can choose between the stable branch, or the development branch. Stable branch will only get major updates, security and critical updates. If unsure, stay on stable.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_RELEASE_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `U0yy0y`
   * 
   * ### Definition
   * ```text
   * Switch to development branch
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_RELEASE_DEVELOP_BTN': TypedIntlMessageGetter<{}>,
  /**
   * Key: `CQoun7`
   * 
   * ### Definition
   * ```text
   * Are you sure you want to change your release channel? Replugged will reload your Discord client.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_RELEASE_MODAL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `QMvHwU`
   * 
   * ### Definition
   * ```text
   * Change release channel
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_RELEASE_MODAL_HEADER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `FlBncS`
   * 
   * ### Definition
   * ```text
   * Switch to stable
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_RELEASE_STABLE_BTN': TypedIntlMessageGetter<{}>,
  /**
   * Key: `QWWrMI`
   * 
   * ### Definition
   * ```text
   * Switch
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_RELEASE_SWITCH': TypedIntlMessageGetter<{}>,
  /**
   * Key: `4ZUrOb`
   * 
   * ### Definition
   * ```text
   * Show update checker toast
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `no`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_TOAST_ENABLED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `JgzaWA`
   * 
   * ### Definition
   * ```text
   * Show an overlay over the client which says updates are being checked for, and if updates are found, prompt you to update. Only applies if update in background is disabled.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `es-419`, `hi`, `no`, `th`
   */
  'REPLUGGED_UPDATES_OPTS_TOAST_ENABLED_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `P+IFIp`
   * 
   * ### Definition
   * ```text
   * Some updates failed!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_UPDATES_TOAST_FAILED_ALL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `A0CErw`
   * 
   * ### Definition
   * ```text
   * Update failed!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_UPDATES_TOAST_FAILED_ONE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `fpehXQ`
   * 
   * ### Definition
   * ```text
   * {count, plural, =1 {# new update} other {# new updates}} available!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`, `zh-CN`
   */
  'REPLUGGED_UPDATES_TOAST_NEW': TypedIntlMessageGetter<{count: number | string}>,
  /**
   * Key: `qPHJU7`
   * 
   * ### Definition
   * ```text
   * No new updates available
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_UPDATES_TOAST_NO_NEW': TypedIntlMessageGetter<{}>,
  /**
   * Key: `6ACGz9`
   * 
   * ### Definition
   * ```text
   * All updates completed successfully
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_UPDATES_TOAST_SUCCESS_ALL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `wKwXx/`
   * 
   * ### Definition
   * ```text
   * Update completed successfully
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_UPDATES_TOAST_SUCCESS_ONE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `DIZGSi`
   * 
   * ### Definition
   * ```text
   * Updater
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_UPDATES_UPDATER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `uMS9cz`
   * 
   * ### Definition
   * ```text
   * Update All
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_UPDATES_UPDATE_ALL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `JdG856`
   * 
   * ### Definition
   * ```text
   * Update to {version}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `lt`, `no`, `ro`, `th`
   */
  'REPLUGGED_UPDATES_UPDATE_TO': TypedIntlMessageGetter<{version: any}>,
  /**
   * Key: `UbD+4l`
   * 
   * ### Definition
   * ```text
   * Updating Replugged…
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_UPDATING': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Gr3VND`
   * 
   * ### Definition
   * ```text
   * Updating…
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_UPDATING_ITEM': TypedIntlMessageGetter<{}>,
  /**
   * Key: `CUNjg/`
   * 
   * ### Definition
   * ```text
   * Everything is up to date.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `es-419`, `hi`, `th`
   */
  'REPLUGGED_UPDATES_UP_TO_DATE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `q8qpAz`
   * 
   * ### Definition
   * ```text
   * Replugged {version, select, dev {[DEV MODE]} other {v{version}}}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `lt`, `no`, `ro`, `sv-SE`, `th`
   */
  'REPLUGGED_VERSION': TypedIntlMessageGetter<{version: 'dev' | any | string}>,
  /**
   * Key: `rHZSz7`
   * 
   * ### Definition
   * ```text
   * View {count, plural, =1 {# Update} other {# Updates}}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `es-419`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `ro`, `sv-SE`, `th`, `zh-CN`
   */
  'REPLUGGED_VIEW_UPDATES': TypedIntlMessageGetter<{count: number | string}>,
};
export default messages;