import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dirname = path.dirname(fileURLToPath(import.meta.url));

const inputPath = path.resolve(dirname, "../i18n/messages/en-US.messages.json");
const outputPath = path.resolve(dirname, "../i18n/en-US.messages.js");

const raw = readFileSync(inputPath, "utf-8");
const messages: Record<string, string> = JSON.parse(raw);

let output = `/* THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY. */\n`;
output += `/* prettier-ignore */\n\n`;
output += `import { defineMessages } from "@discord/intl";\n\n`;
output += `export default defineMessages(${JSON.stringify(messages, null, 2)});`;

writeFileSync(outputPath, output, "utf-8");
