name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Build TypeScript and bundle into asar
        run: pnpm run bundle

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.asar"
          makeLatest: true
