name: Update Messages

on:
  push:
    branches:
      - main
    paths:
      - "i18n/messages/*.messages.json"

permissions:
  contents: write

jobs:
  generate-messages:
    name: Generate Messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Run Generate Messages
        run: pnpm run generate-messages

      - name: Publish
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add i18n
          git diff-index --quiet HEAD || git commit -m "chore(i18n): update message definitions [skip ci]"
          git push
